name: Java Code Format and Build Check

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  format-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Install dependencies
      - name: Install Maven dependencies
        run: mvn dependency:resolve

      # Check code format using Spotless
      - name: Check code format
        run: mvn spotless:check

      # Build the project
      - name: Build project
        run: mvn clean install
